AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/ModuleLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
